# Generated by Django 3.1.4 on 2020-12-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20201202_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.URLField(),
        ),
    ]
