# Generated by Django 3.1.4 on 2020-12-03 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_auto_20201202_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.ManyToManyField(related_name='views_video', to=settings.AUTH_USER_MODEL),
        ),
    ]
