# Generated by Django 3.1.4 on 2020-12-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20201203_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='views',
        ),
        migrations.AddField(
            model_name='item',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
