# Generated by Django 3.1.4 on 2020-12-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_item_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
    ]
