# Generated by Django 3.1.4 on 2020-12-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_item_video_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video_title',
            field=models.CharField(max_length=300),
        ),
    ]
